# Immagine base con supporto CUDA e cuDNN
FROM nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04

# === Variabili ambiente ===
ENV PATH="/root/.cargo/bin:$PATH:/usr/local/cuda/bin:$PATH"
ENV DEBIAN_FRONTEND=noninteractive
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
ENV APP_ENV=production

# === Sistema & Dev ===
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    curl \
    apt-transport-https \
    freetds-bin \
    freetds-dev \
    unixodbc \
    unixodbc-dev \
    gcc \
    g++ \
    make \
    zlib1g-dev \
    libncurses5-dev \
    libgdbm-dev \
    libnss3-dev \
    libssl-dev \
    libreadline-dev \
    libffi-dev \
    libsqlite3-dev \
    openjdk-11-jdk \
    cmake \
    ninja-build \
    git \
    gnupg \
    wget \
    zip \
    unzip \
    clang \
    python3-dev \
    python3-pip \
    python3-setuptools \
    sqlite3 \
    libsqlite3-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# === Python ===
RUN pip install --upgrade pip

# === Rust & Cargo ===
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# === ODBC per SQL Server ===
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql18 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# === TensorFlow ===
RUN pip install tensorflow

# === App setup ===
WORKDIR /app
RUN mkdir -p /app/logs /app/export
COPY requirements.txt .

# Dipendenze progetto
RUN pip install uvicorn pyodbc && pip install --user -r requirements.txt